export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced
export PATH=~/Library/Python/3.6/bin:/usr/bin:/usr/sbin:/bin:/sbin/:/usr/local/bin
export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH
alias ls='ls -GFh'
alias senv='source env/bin/activate'
alias prof='code ~/.bash_profile'
alias sprof='source ~/.bash_profile'
